source 'https://rubygems.org'

ruby '2.2.4'

gem 'rspec'
gem 'pacto', '= 0.4.0.rc1'
gem 'pacto-server', '= 0.4.0.rc1'
gem 'httpclient'
gem 'json'
gem 'sinatra'
gem 'thin'
gem 'rack'
gem 'json-schema'
gem 'rubocop'
gem 'guard'
gem 'guard-rake'
